"""+messageinfo model

Revision ID: 224556c52e8b
Revises: 4cddd9bd2ac8
Create Date: 2025-07-07 16:25:17.920643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224556c52e8b'
down_revision: Union[str, None] = '4cddd9bd2ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_id'), table_name='session')
    # ### end Alembic commands ###
