"""+messageinfo is_quest

Revision ID: 76a7f21ed975
Revises: 224556c52e8b
Create Date: 2025-07-08 12:53:58.480836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a7f21ed975'
down_revision: Union[str, None] = '224556c52e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_guest')
    # ### end Alembic commands ###
