"""+sessioninfomodel

Revision ID: d5f4163a7420
Revises: e2ab5fab3fea
Create Date: 2025-07-07 15:15:38.561840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f4163a7420'
down_revision: Union[str, None] = 'e2ab5fab3fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
