"""+sessioninfo is_quest

Revision ID: f83910494eae
Revises: 76a7f21ed975
Create Date: 2025-07-08 12:54:50.143713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83910494eae'
down_revision: Union[str, None] = '76a7f21ed975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('is_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'is_guest')
    # ### end Alembic commands ###
