from api.database.database import Base
from sqlalchemy import BIGINT, FLOAT, TEXT, Column, Integer, String, Boolean, TIMESTAMP


class Product(Base):
    __tablename__ = "Product"
    index = Column(BIGINT, primary_key=True, index=True, nullable=True)
    prodID = Column(BIGINT)
    aID = Column(BIGINT)
    barcode = Column(FLOAT)
    productName = Column(TEXT)
    vendorCode = Column(TEXT)
    vendor = Column(TEXT)
    vendorID = Column(BIGINT)
    vendorCountry = Column(TEXT)
    vendorDescription = Column(TEXT)
    prodCountry = Column(TEXT)
    retailPrice = Column(BIGINT)
    baseRetailPrice = Column(BIGINT)
    wholePrice = Column(FLOAT)
    baseWholePrice = Column(FLOAT)
    userPrice = Column(FLOAT)
    discount = Column(BIGINT)
    stock = Column(BIGINT)
    shippingDate = Column(TEXT)
    description = Column(TEXT)
    brutto = Column(FLOAT)
    bruttoKg = Column(FLOAT)
    batteries = Column(FLOAT)
    pack = Column(TEXT)
    material = Column(TEXT)
    lenght = Column(FLOAT)
    diameter = Column(FLOAT)
    collection = Column(TEXT)
    images = Column(TEXT)
    customCatalogueId = Column(BIGINT)
    customCatalogueParentId = Column(BIGINT)
    customCatalogueName = Column(TEXT)
    category1 = Column(TEXT)
    category2 = Column(TEXT)
    category3 = Column(TEXT)
    category4 = Column(TEXT)
    category5 = Column(FLOAT)
    categoryPath = Column(TEXT)
    color = Column(TEXT)
    colorUrl = Column(TEXT)
    size = Column(TEXT)
    novelties = Column(BIGINT)
    superSale = Column(FLOAT)
    bestseller = Column(BIGINT)
    prodUrl = Column(TEXT)
    function = Column(TEXT)
    addFunction = Column(FLOAT)
    vibration = Column(FLOAT)
    volume = Column(FLOAT)
    modelYear = Column(FLOAT)
    imgStatus = Column(BIGINT)
    readyToGo = Column(BIGINT)
    p5sStock = Column(BIGINT)
    stopPromo = Column(BIGINT)
    bruttoLength = Column(FLOAT)
    bruttoWidth = Column(FLOAT)
    bruttoHeight = Column(FLOAT)
    currency = Column(TEXT, default='RUB')
    mpRule = Column(BIGINT)
    manual = Column(FLOAT)
    composition = Column(FLOAT)
    genderSpecific = Column(FLOAT)
    img1 = Column(TEXT)
    img2 = Column(TEXT)
    img3 = Column(TEXT)
    img4 = Column(TEXT)
    img5 = Column(TEXT)
    img6 = Column(TEXT)
    img7 = Column(TEXT)
    img8 = Column(TEXT)
    img9 = Column(TEXT)
    img10 = Column(TEXT)
    packLength = Column(FLOAT)
    packWidth = Column(FLOAT)
    packHeight = Column(FLOAT)
    notStandardPack = Column(BIGINT)

    def __str__(self):
        return str(self.productName)
    
class Catalog(Base):
    __tablename__ = "Catalog"
    id = Column(Integer, primary_key=True, index=True)
    genderSpecific = Column(Integer)
    category1 = Column(String)
    category = Column(String)
    subcategory = Column(String)
    catID = Column(Integer)
    parentID = Column(Integer)
    
class Promos(Base):
    __tablename__ = "Promos"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    description = Column(String, nullable=True)
    startDate = Column(TIMESTAMP, nullable=True)
    endDate = Column(TIMESTAMP, nullable=True)
    maxDiscount = Column(Integer, nullable=True)
    category = Column(String, nullable=True)
    subcategory = Column(String, nullable=True)
    vendor = Column(String, nullable=True)
    products = Column(String, nullable=True)
    image_url = Column(String, nullable=True)